"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const cart_controller_1 = require("../controllers/cart.controller");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const router = (0, express_1.Router)();
router.post("/create-cart", auth_middleware_1.authenticateUser, cart_controller_1.addToCartController);
router.get("/get-cart", auth_middleware_1.authenticateUser, cart_controller_1.getUserCartController);
router.delete("/delete-cart/:productId", auth_middleware_1.authenticateUser, cart_controller_1.removeFromCartController);
exports.default = router;
