"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_routes_1 = __importDefault(require("./auth.routes"));
const categories_routes_1 = __importDefault(require("./categories.routes"));
const product_routes_1 = __importDefault(require("./product.routes"));
const review_routes_1 = __importDefault(require("./review.routes"));
const cart_routes_1 = __importDefault(require("./cart.routes"));
const order_routes_1 = __importDefault(require("./order.routes"));
const payment_routes_1 = __importDefault(require("./payment.routes"));
const router = (0, express_1.Router)();
router.use("/auth", auth_routes_1.default);
router.use("/categories", categories_routes_1.default);
router.use("/products", product_routes_1.default);
router.use("/reviews", review_routes_1.default);
router.use("/cart", cart_routes_1.default);
router.use("/orders", order_routes_1.default);
router.use("/payments", payment_routes_1.default);
exports.default = router;
